repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # použijte konkrétní verzi pro stabilitu
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0  # použijte konkrétní verzi pro stabilitu
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0  # Nahraďte za poslední dostupnou verzi
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pylint
    rev: v2.17.5  # Nahraďte za poslední dostupnou verzi
    hooks:
      - id: pylint
